version: 1.0.{build}
environment:
  PYTHON: C:\Python37-x64
  PYTHON_VERSION: 3.7.1
  PYTHON_ARCH: 64
  CONAN_UPLOAD: https://api.bintray.com/conan/kudzurunner/conan-stable
  CONAN_REMOTE: conan-stable
  CONAN_REFERENCE: opencv/4.0.1
  CONAN_USERNAME: kudzurunner
  CONAN_CHANNEL: stable
  CONAN_PASSWORD:
    secure: FHRzS1Qt5LEb3S+po6y9BkjaPm/d5gv56M9ZC90wpJVIJs/f4ljLdVoXhbqk4jEZ
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CONAN_VISUAL_VERSIONS: 14
    CONAN_VISUAL_RUNTIMES: "MD,MDd"
    CONAN_ARCHS: x86_64
install:
- |
    appveyor DownloadFile https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_windows-exe -FileName cuda_8.0.61_windows.exe
    appveyor DownloadFile https://developer.nvidia.com/compute/cuda/8.0/Prod2/patches/2/cuda_8.0.61.2_windows-exe -FileName cuda_8.0.61.2_windows.exe
    appveyor Downloadfile http://developer.download.nvidia.com/compute/redist/cudnn/v7.0.5/cudnn-8.0-windows7-x64-v7.zip -FileName cudnn.zip

    cuda_8.0.61_windows.exe -s compiler_8.0 cublas_8.0 cublas_dev_8.0 cudart_8.0 cufft_8.0 cufft_dev_8.0 curand_8.0 curand_dev_8.0 cusolver_8.0 cusolver_dev_8.0 cusparse_8.0 cusparse_dev_8.0 nvrtc_8.0 nvrtc_dev_8.0 npp_8.0 npp_dev_8.0
    cuda_8.0.61.2_windows.exe -s cublas_8.0 cublas_dev_8.0
    7z x cudnn.zip
    copy cuda\include\cudnn.h "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include\"
    copy cuda\lib\x64\cudnn.lib "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64\"
    copy cuda\bin\cudnn64_7.dll "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\"

    dir .
    dir "%ProgramFiles%"
    dir "C:\Program Files"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0"
    dir "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin"

    set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;%PYTHON%;%PYTHON%/Scripts/;%PATH%
    nvcc -V

    pip install conan --upgrade
    pip install conan_package_tools
    conan remote add conan-stable https://api.bintray.com/conan/kudzurunner/conan-stable
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    conan user

build: off
test_script:
- cmd: python build.py
deploy: off